theme: jekyll-theme-cayman
title: PixiJS Guides
description: User Guides for working with PixiJS
baseurl: /guides
collections:
  basics:
    output: true
    permalink: /:collection/:name
  production:
    output: true
    permalink: /:collection/:name
  advanced:
    output: true
