# Base setup
theme: jekyll-theme-primer
title: PixiJS Guides
description: User Guides for working with PixiJS

# Deploy endpoint, use relative_url filter to apply
baseurl: /guides

# Set up our collections of guides
collections:
  basics:
    output: true
    order:
      - what-pixijs-is.md
      - what-pixijs-is-not.md
      - getting-started.md
      - architecture-overview.md
      - render-loop.md
      - scene-graph.md
      - display-object.md
      - textures.md
      - sprites.md
      - sprite-sheets.md
      - text.md
      - containers.md
      - graphics.md
      - interaction.md
      - masks.md
      - audio.md
  production:
    output: true
    order:
      - resolution.md
      - resource-loading.md
      - memory-management.md
      - network-optimization.md
      - performance-tuning.md
      - scenes.md
      - bundlers.md
      - canvas-renderer.md
  advanced:
    output: true
    order:
      - pixi-core.md
      - particles.md
      - filters.md

# Overall defaults
defaults:
  -
    values:
      layout: "default"
