name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: npm run g
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.0
        with:
          email: sukantk2002@outlook.com
          build_dir: guides
          branch: gh-pages
          commit_message: Generate guides site, with webdoc
