name: Build and deploy webdoc site

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm
        run: npm install -g npm@7
      - name: Install Dependencies
        run: npm install
      - name: Generate
        run: npm run build
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.JEKYLL_PAT }}
        with:
          email: sukantk2002@outlook.com
          build_dir: guides
          branch: gh-pages
          commit_message: Generate guides site, with webdoc
